"""Create animals table

Revision ID: cb3a160eff35
Revises: aff75dd240c1
Create Date: 2023-12-21 18:23:13.776297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb3a160eff35'
down_revision: Union[str, None] = 'aff75dd240c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contacts',
    sa.Column('pk', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.String(length=13), nullable=False),
    sa.Column('telegram', sa.String(length=128), nullable=True),
    sa.Column('instagram', sa.String(length=128), nullable=True),
    sa.Column('twitter', sa.String(length=128), nullable=True),
    sa.Column('website', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('pk')
    )
    op.create_table('shelters',
    sa.Column('pk', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('address', sa.String(length=512), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.pk'], ),
    sa.PrimaryKeyConstraint('pk')
    )
    op.create_table('animals',
    sa.Column('pk', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('sex', sa.Enum('female', 'male', name='sexenum'), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('species', sa.Enum('cat', 'kitty', 'dog', 'puppy', 'other', name='speciesenum'), nullable=False),
    sa.Column('since_time', sa.DateTime(), nullable=False),
    sa.Column('shelter_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['shelter_id'], ['shelters.pk'], ),
    sa.PrimaryKeyConstraint('pk')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('animals')
    op.drop_table('shelters')
    op.drop_table('contacts')
    # ### end Alembic commands ###
