"""change animals remove policy

Revision ID: 4ccf95066299
Revises: cb3a160eff35
Create Date: 2023-12-21 18:27:18.277711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ccf95066299'
down_revision: Union[str, None] = 'cb3a160eff35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('animals', 'shelter_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('animals_shelter_id_fkey', 'animals', type_='foreignkey')
    op.create_foreign_key(None, 'animals', 'shelters', ['shelter_id'], ['pk'], ondelete='SET NULL')
    op.alter_column('shelters', 'contact_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('shelters_contact_id_fkey', 'shelters', type_='foreignkey')
    op.create_foreign_key(None, 'shelters', 'contacts', ['contact_id'], ['pk'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shelters', type_='foreignkey')
    op.create_foreign_key('shelters_contact_id_fkey', 'shelters', 'contacts', ['contact_id'], ['pk'])
    op.alter_column('shelters', 'contact_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'animals', type_='foreignkey')
    op.create_foreign_key('animals_shelter_id_fkey', 'animals', 'shelters', ['shelter_id'], ['pk'])
    op.alter_column('animals', 'shelter_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
