"""shelter phone_number.nullable = false

Revision ID: b4e64cafbc52
Revises: ebbed8350f83
Create Date: 2023-12-27 16:19:51.892283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4e64cafbc52'
down_revision: Union[str, None] = 'ebbed8350f83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shelters', 'phone_number',
               existing_type=sa.VARCHAR(length=13),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shelters', 'phone_number',
               existing_type=sa.VARCHAR(length=13),
               nullable=True)
    # ### end Alembic commands ###
