"""inititial commit

Revision ID: ebbed8350f83
Revises: 
Create Date: 2023-12-27 16:17:09.744760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebbed8350f83'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('advertisement',
    sa.Column('pk', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('image_path', sa.Text(), nullable=False),
    sa.Column('published_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('pk')
    )
    op.create_table('shelters',
    sa.Column('pk', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('address', sa.String(length=512), nullable=False),
    sa.Column('phone_number', sa.String(length=13), nullable=True),
    sa.Column('telegram', sa.String(length=128), nullable=True),
    sa.Column('instagram', sa.String(length=128), nullable=True),
    sa.Column('twitter', sa.String(length=128), nullable=True),
    sa.Column('website', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('pk')
    )
    op.create_table('animals',
    sa.Column('pk', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('sex', sa.Enum('female', 'male', name='sexenum'), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('species', sa.Enum('cat', 'kitty', 'dog', 'puppy', 'other', name='speciesenum'), nullable=False),
    sa.Column('since_time', sa.DateTime(), nullable=False),
    sa.Column('shelter_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['shelter_id'], ['shelters.pk'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('pk')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('animals')
    op.drop_table('shelters')
    op.drop_table('advertisement')
    # ### end Alembic commands ###
