"""add image_path to animals

Revision ID: 9a281f45fd94
Revises: b4e64cafbc52
Create Date: 2024-01-08 17:12:08.125337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a281f45fd94'
down_revision: Union[str, None] = 'b4e64cafbc52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('animals', sa.Column('image_path', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('animals', 'image_path')
    # ### end Alembic commands ###
